name: 'workshop'
version: '1.0.0'
config-version: 2

profile: 'workshop'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  workshop:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
